version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-tpc-portal-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: testdb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - go-mysql-network

volumes:
  mysql_data:

networks:
  go-mysql-network:
    driver: bridge
